22-03-23 20:21:38 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x000001DE843F05E0>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 93, in get_next_funding_rate
    url = f'{self.okex_url}/api/v5/public/funding-rate'
AttributeError: 'CommsOKX' object has no attribute 'okex_url'
22-03-23 20:21:38 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x000001DE843F05E0>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 93, in get_next_funding_rate
    url = f'{self.okex_url}/api/v5/public/funding-rate'
AttributeError: 'CommsOKX' object has no attribute 'okex_url'
22-03-23 20:21:39 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x000001DE843F05E0>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 93, in get_next_funding_rate
    url = f'{self.okex_url}/api/v5/public/funding-rate'
AttributeError: 'CommsOKX' object has no attribute 'okex_url'
22-03-23 20:21:41 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x000001DE843F05E0>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 93, in get_next_funding_rate
    url = f'{self.okex_url}/api/v5/public/funding-rate'
AttributeError: 'CommsOKX' object has no attribute 'okex_url'
22-03-23 20:21:43 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x000001DE843F05E0>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 93, in get_next_funding_rate
    url = f'{self.okex_url}/api/v5/public/funding-rate'
AttributeError: 'CommsOKX' object has no attribute 'okex_url'
22-03-23 20:21:43 	 CRITICAL 	 utils.py - try5times_wrapper: 	 <function CommsOKX.get_next_funding_rate at 0x000001DE843F05E0> failed to work after 5 attempts.
22-03-23 20:25:12 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x0000020992080550>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 98, in get_next_funding_rate
    funding_rates[pair] = response['data'][0]['fundingRate']
IndexError: list index out of range
22-03-23 20:25:21 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x0000020992080550>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 98, in get_next_funding_rate
    funding_rates[pair] = response['data'][0]['fundingRate']
IndexError: list index out of range
22-03-23 20:25:31 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x0000020992080550>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 98, in get_next_funding_rate
    funding_rates[pair] = response['data'][0]['fundingRate']
IndexError: list index out of range
22-03-23 20:25:42 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x0000020992080550>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 98, in get_next_funding_rate
    funding_rates[pair] = response['data'][0]['fundingRate']
IndexError: list index out of range
22-03-23 20:25:54 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_next_funding_rate at 0x0000020992080550>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 98, in get_next_funding_rate
    funding_rates[pair] = response['data'][0]['fundingRate']
IndexError: list index out of range
22-03-23 20:25:54 	 CRITICAL 	 utils.py - try5times_wrapper: 	 <function CommsOKX.get_next_funding_rate at 0x0000020992080550> failed to work after 5 attempts.
22-03-24 01:25:36 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_historical_funding_rates at 0x000001F93CAC4670>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in get_historical_funding_rates
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in <dictcomp>
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
TypeError: unsupported operand type(s) for /: 'str' and 'int'
22-03-24 01:25:37 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_historical_funding_rates at 0x000001F93CAC4670>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in get_historical_funding_rates
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in <dictcomp>
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
TypeError: unsupported operand type(s) for /: 'str' and 'int'
22-03-24 01:25:38 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_historical_funding_rates at 0x000001F93CAC4670>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in get_historical_funding_rates
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in <dictcomp>
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
TypeError: unsupported operand type(s) for /: 'str' and 'int'
22-03-24 01:25:41 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_historical_funding_rates at 0x000001F93CAC4670>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in get_historical_funding_rates
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in <dictcomp>
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
TypeError: unsupported operand type(s) for /: 'str' and 'int'
22-03-24 01:25:43 	 ERROR 	 utils.py - try5times_wrapper: 	 Error found when running <function CommsOKX.get_historical_funding_rates at 0x000001F93CAC4670>.
Traceback (most recent call last):
  File "C:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\utils.py", line 14, in try5times_wrapper
    return function(self, *args, **kwargs)
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in get_historical_funding_rates
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
  File "c:\Users\micha\Documents\XXX Capital Management\Code\new_crypto_program\scripts\comms_okx.py", line 148, in <dictcomp>
    pair_rates = {datetime.fromtimestamp(d['fundingTime']/1000): float(d['fundingRate']) for d in data}
TypeError: unsupported operand type(s) for /: 'str' and 'int'
22-03-24 01:25:43 	 CRITICAL 	 utils.py - try5times_wrapper: 	 <function CommsOKX.get_historical_funding_rates at 0x000001F93CAC4670> failed to work after 5 attempts.
